name: Build and Export Artifact For Windows

on:
  push:
    branches: [main, build-workflow] # Remember to remove
  pull_request:
    branches: [main]

env:
  IREE_SOURCE_DIR: ${{ github.workspace }}/thirdparty/iree
  IREE_BUILD_DIR: ${{ github.workspace }}/build_iree
  IREE_HOST_BIN_DIR: ${{ github.workspace }}/iree_dist
  SOURCE_DIR: ${{ github.workspace }}
  BUILD_DIR: ${{ github.workspace }}/build

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        target: [windows]
        arch: [x86_64, x86_32]
        build_type: [release, debug]
        include:
          # Build type to cmake keyword.
          - build_type: release
            cmake_build_type_keyword: Release

          - build_type: debug
            cmake_build_type_keyword: RelWithDebInfo

          # Define host for each target.
          - os: windows-2022
            target: windows
            lib_suffix: dll

          # Define toolchain data.
          - target: windows
            arch: x86_64
            cmake_arch_keyword: x64

          - target: windows
            arch: x86_32
            cmake_arch_keyword: WIN32

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Set up MSVC Dev Cmd
        uses: ilammy/msvc-dev-cmd@7315a94840631165970262a99c72cfb48a65d25d # v1.12.0
        with:
          arch: ${{ matrix.cmake_arch_keyword }}

      # Setup CMake
      - name: Set up CMake for Windows
        shell: cmd
        run: |
          if not exist "%BUILD_DIR%" mkdir "%BUILD_DIR%"
          cd "%BUILD_DIR%"
          "%VCINSTALLDIR%\\vcvarsall.bat" "${{ matrix.cmake_arch_keyword }}"
          cmake "%SOURCE_DIR%" -G Ninja -DCMAKE_BUILD_TYPE="${{ matrix.cmake_build_type_keyword }}"

      - name: Build project
        shell: bash
        run: cmake --build "${BUILD_DIR}"

      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          name: "libiree-gd.${{ matrix.target }}.${{ matrix.build_type }}.${{ matrix.arch }}.${{ matrix.lib_suffix }}"
          path: "${BUILD_DIR}/lib/libiree-gd.${{ matrix.target }}.${{ matrix.build_type }}.${{ matrix.arch }}.${{ matrix.lib_suffix }}"
