name: Build and Export Artifact For Windows

on:
  push:
    branches: [main, build-workflow] # Remember to remove
  pull_request:
    branches: [main]

env:
  SOURCE_DIR: ${{ github.workspace }}
  BUILD_DIR: ${{ github.workspace }}/build

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        target: [windows]
        arch: [x86_64, x86_32]
        build_type: [release, debug]
        include:
          - cmake_generator_keyword: Ninja
          # Build type to cmake keyword.
          - build_type: release
            cmake_build_type_keyword: Release

          - build_type: debug
            cmake_build_type_keyword: RelWithDebInfo

          # Define host for each target.
          - os: windows-2022
            target: windows
            lib_suffix: dll

          # Define toolchain data.
          - target: windows
            arch: x86_64
            cmake_arch_keyword: WIN64
            cmake_generator_keyword: Visual Studio 17 2022

          - target: windows
            arch: x86_32
            cmake_arch_keyword: WIN32
            cmake_generator_keyword: Visual Studio 17 2022

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          msbuild-architecture: ${{ matrix.cmake_arch_keyword }}

      # Setup CMake
      - name: Set up CMake for Windows
        shell: bash
        run: |
          if [ ! -d "${BUILD_DIR}" ]; then
            mkdir "${BUILD_DIR}"
          fi
          cd "${BUILD_DIR}"
          cmake "${SOURCE_DIR}" -G "${{ matrix.cmake_generator_keyword }}" -DCMAKE_BUILD_TYPE="${{ matrix.cmake_build_type_keyword }}" \
            -DCMAKE_GENERATOR_PLATFORM="${{ matrix.cmake_arch_keyword }}"

      - name: Build project
        shell: bash
        run: cmake --build "${BUILD_DIR}"

      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          name: "libiree-gd.${{ matrix.target }}.${{ matrix.build_type }}.${{ matrix.arch }}.${{ matrix.lib_suffix }}"
          path: "${BUILD_DIR}/lib/libiree-gd.${{ matrix.target }}.${{ matrix.build_type }}.${{ matrix.arch }}.${{ matrix.lib_suffix }}"
