name: Build and Export Artifact for Mac OS

on:
  push:
    branches: [main, build-workflow] # Remember to remove
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        target: [macos]
        arch: [universal]
        build_type: [release, debug]
        include:
          # Build type to cmake keyword.
          - build_type: release
            cmake_build_type_keyword: Release

          - build_type: debug
            cmake_build_type_keyword: RelWithDebInfo

          - os: macos-latest
            target: macos
            lib_suffix: dylib

          # Define toolchain data.
          - target: macos
            arch: universal
            cmake_arch_keyword: arm64;x86_64

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      # Setup CMake
      - name: Set up CMake for MacOS
        shell: bash
        run: |
          if [ ! -d "${{ github.workspace }}/build" ]; then
            mkdir "${{ github.workspace }}/build"
          fi
          cd "${{ github.workspace }}/build"
          cmake "${{ github.workspace }}" -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type_keyword }} \
            -DPLATFORM="${{ matrix.cmake_arch_keyword }}"

      - name: Build project
        shell: bash
        run: ninja -C "${{ github.workspace }}/build"

      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          name: "libiree-gd.${{ matrix.target }}.${{ matrix.build_type }}.${{ matrix.arch }}.${{ matrix.lib_suffix }}"
          path: "${{ github.workspace }}/build/lib/*"
          if-no-files-found: error
